QuanLyTruongDaiHoc/QuanLyTruongDaiHoc/Areas/Admin/Controllers/QuanLyLichThiController.cs
using QuanLyTruongDaiHoc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyTruongDaiHoc.Areas.Admin.Controllers
{
    public class QuanLyLichThiController : Controller
    {
        QuanLyDaiHocEntities db = new QuanLyDaiHocEntities();
        // GET: Admin/QuanLyLichThi
        bool checkLogin(string prevUrl)
        {
            if (Session["TaikhoanQT"] == null)
            {
                Session["PreviousURL"] = "~/Admin/QuanLyLichThi/" + prevUrl;
                Session["LoaiTK"] = Init.TaiKhoanQT;
                return false;
            }
            return true;
        }
        public ActionResult DanhSachKhoaHocLichThi()
        {
            if (!checkLogin("DanhSachKhoaHocLichThi"))
            {
                return RedirectToAction("DangNhap", "Admin");
            }
            var kh = db.tb_KhoaHoc.ToList();
            return View(kh);
        }

        public ActionResult XemLichThi(int? id)
        {
            var kh = db.tb_KhoaHoc.SingleOrDefault(n => n.ID == id);
            ViewBag.KH = kh;
            var lichThi = kh.tb_ThongTinNgayThi;
            ViewBag.DSSV = kh.tb_DangKyMonHoc.ToList();
            return View(lichThi);
        }

        [HttpPost]
        public ActionResult LuuThayDoi(FormCollection collection)
        {
            int id = int.Parse(collection["hidden"]);

            var kh = db.tb_KhoaHoc.SingleOrDefault(n => n.ID == id);

            var lt = kh.tb_ThongTinNgayThi.ToList();

            foreach (var item in lt)
            {
                if (string.IsNullOrEmpty(collection["lt-" + item.ID]))
                {
                    db.tb_ThongTinNgayThi.Remove(item);
                }
            }
            db.SaveChanges();
            Session["SuccessLuuThayDoi"] = "Đã lưu thay đổi thành công";

            return RedirectToAction("XemLichThi", new { id = id });
        }

        public ActionResult ThemLichKhoaHoc(int? id)
        {
            var kh = db.tb_KhoaHoc.SingleOrDefault(n => n.ID == id);
            ViewBag.ID_KhoaHoc = kh.ID;
            var dsgv = db.tb_GiangVien.Where(n => n.tb_KhoaHoc.FirstOrDefault(s => s.ID == kh.ID) == null);
            ViewBag.DSPH = db.tb_PhongHoc.Where(n => n.TrangThai == true).ToList();
            return PartialView(dsgv);
        }

        [HttpPost]
        public ActionResult ThemLichKhoaHoc(FormCollection collection)
        {
            int id = int.Parse(collection["hidden"]);
            DateTime ngaythi = DateTime.Parse(collection["Ngaythi"]);
            int idph = int.Parse(collection["Phongthi"]);
            string giobatdau = collection["Giobatdau"];
            int thoiluong = int.Parse(collection["Thoiluong"]);
            int id_gt1 = int.Parse(collection["Giamthi1"]);
            int id_gt2 = int.Parse(collection["Giamthi2"]);

            tb_ThongTinNgayThi ngt = new tb_ThongTinNgayThi();
            ngt.GioBatDau = giobatdau;
            ngt.ID_GiamThi1 = id_gt1;
            ngt.ID_GiamThi2 = id_gt2;
            ngt.ID_KhoaHoc = id;
            ngt.NgayThi = ngaythi;
            ngt.ThoiLuong = thoiluong;
            ngt.PhongThi = idph;
            db.tb_ThongTinNgayThi.Add(ngt);
            db.SaveChanges();

            Session["SuccessThemLichKhoaHoc"] = "Đã thêm lịch thành công";
            return RedirectToAction("XemLichThi", new { id = id });
        }

        public ActionResult XoaLichThi(int? id)
        {
            var lt = db.tb_ThongTinNgayThi.SingleOrDefault(n => n.ID == id);
            return PartialView(lt);
        }


        public ActionResult XacNhanXoaLichThi(int? id)
        {
            var lt = db.tb_ThongTinNgayThi.SingleOrDefault(n => n.ID == id);
            int? id_kh = lt.ID_KhoaHoc;
            db.tb_ThongTinNgayThi.Remove(lt);
            try
            {
                db.SaveChanges();
                Session["SuccessXoaLichThi"] = "Xoá lịch thi thất bại vì lịch đang được sử dụng";
            }
            catch
            {
                Session["ErrorXoaLichThi"] = "Xoá lịch thi thất bại vì lịch đang được sử dụng";
            }

            return RedirectToAction("XemLichThi", new { id = id_kh });
        }


        public ActionResult XemPhongThi(int? id)
        {
            var lt = db.tb_ThongTinNgayThi.SingleOrDefault(n => n.ID == id);
            var dkmh = lt.tb_KhoaHoc.tb_DangKyMonHoc.ToList();
            foreach (var item in dkmh)
            {
                if (db.tb_ChiTietLichThi.SingleOrDefault(n => n.ID_SinhVien == item.ID_SinhVien && n.ID_ThongTinNgayThi != id) != null)
                {
                    dkmh.Remove(item);
                }
            }
            ViewBag.LT = lt;
            ViewBag.CTLT = lt.tb_ChiTietLichThi.ToList();
            ViewBag.PT = db.tb_PhongHoc;
            return View(dkmh);
        }

        public ActionResult ChinhSuaLichThi(int? id)
        {
            var lt = db.tb_ThongTinNgayThi.SingleOrDefault(n => n.ID == id);
            ViewBag.GV = db.tb_GiangVien.ToList();
            ViewBag.DSPH = db.tb_PhongHoc.ToList();
            return PartialView(lt);
        }

        [HttpPost]
        public ActionResult ChinhSuaLichThi(FormCollection collection)
        {
            var id = int.Parse(collection["hidden"]);
            var lt = db.tb_ThongTinNgayThi.SingleOrDefault(n => n.ID == id);

            lt.ID_GiamThi1 = int.Parse(collection["GiamThi1"]);
            lt.ID_GiamThi2 = int.Parse(collection["GiamThi2"]);
            lt.NgayThi = DateTime.Parse(collection["Ngaythi"]);
            lt.PhongThi = int.Parse(collection["Phongthi"]);
            lt.GioBatDau = collection["Giobatdau"];
            lt.ThoiLuong = int.Parse(collection["Thoiluong"]);
            db.Entry(lt).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            Session["SuccessChinhSuaLichThi"] = "Đã cập nhật lịch thi";
            return RedirectToAction("XemPhongThi", new { id = id });
        }

        public ActionResult DanhSachSinhVienDangKy(int? id)
        {
            ViewBag.ID_PT = id;
            var lt = db.tb_ThongTinNgayThi.SingleOrDefault(n => n.ID == id);
            var dssvdk = db.tb_DangKyMonHoc.Where(n => n.ID_KhoaHoc == lt.ID_KhoaHoc);
            ViewBag.CTLT = lt.tb_ChiTietLichThi.ToList();
            return PartialView(dssvdk);
        }

        public ActionResult SinhVienPhongThi(int? id)
        {
            var dssvdk = db.tb_ChiTietLichThi.Where(n => n.ID_ThongTinNgayThi == id);
            return PartialView(dssvdk);
        }

        public ActionResult ThemSVPhongThi(int? id, int? idlt)
        {
            var dkm = db.tb_DangKyMonHoc.SingleOrDefault(n => n.ID == id);
            var lt = db.tb_ThongTinNgayThi.SingleOrDefault(n => n.ID == idlt);
            var ctlt = db.tb_ChiTietLichThi.SingleOrDefault(n => n.ID_ThongTinNgayThi != idlt && n.ID_SinhVien == dkm.ID_SinhVien && n.tb_ThongTinNgayThi.ID_KhoaHoc == lt.ID_KhoaHoc);

            if (ctlt != null)
            {
                db.tb_ChiTietLichThi.Remove(ctlt);
                db.SaveChanges();
            }
            tb_ChiTietLichThi ct = new tb_ChiTietLichThi();
            ct.ID_SinhVien = dkm.ID_SinhVien;
            ct.ID_ThongTinNgayThi = lt.ID;
            db.tb_ChiTietLichThi.Add(ct);
            db.SaveChanges();
            return RedirectToAction("SinhVienPhongThi", new { id = idlt });

        }
        public ActionResult LoaiBoSvPhongThi2(int? id)
        {
            var dkm = db.tb_DangKyMonHoc.SingleOrDefault(n => n.ID == id);

            var ttnt = dkm.tb_KhoaHoc.tb_ThongTinNgayThi;
            int? id_lt = null;
            foreach (var tt in ttnt)
            {
                var ct = tt.tb_ChiTietLichThi.SingleOrDefault(n => n.ID_SinhVien == dkm.ID_SinhVien);
                if (ct != null)
                {
                    id_lt = ct.ID_ThongTinNgayThi;
                    db.tb_ChiTietLichThi.Remove(ct);
                    db.SaveChanges();
                    break;
                }
            }
            return RedirectToAction("SinhVienPhongThi", new { id = id_lt });
        }

        public ActionResult LoaiBoSvPhongThi(int? id)
        {
            var dkm = db.tb_DangKyMonHoc.SingleOrDefault(n => n.ID == id);

            var ttnt = dkm.tb_KhoaHoc.tb_ThongTinNgayThi;
            int? id_lt = null;
            foreach (var tt in ttnt)
            {
                var ct = tt.tb_ChiTietLichThi.SingleOrDefault(n => n.ID_SinhVien == dkm.ID_SinhVien);
                if (ct != null)
                {
                    id_lt = ct.ID_ThongTinNgayThi;
                    db.tb_ChiTietLichThi.Remove(ct);
                    db.SaveChanges();
                    break;
                }
            }
            return RedirectToAction("DanhSachSinhVienDangKy", new { id = id_lt });
        }
    }
}

QuanLyTruongDaiHoc/QuanLyTruongDaiHoc/Areas/Admin/Views/QuanLyLichThi/ChinhSuaLichThi.cshtml
@model QuanLyTruongDaiHoc.Models.tb_ThongTinNgayThi
@using QuanLyTruongDaiHoc.Models;

@{ 

    List<tb_GiangVien> gv = (List<tb_GiangVien>)ViewBag.GV;
}

<div class="modal fade" id="modalChinhSuaLichThi">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Thêm lịch khoá học</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("ChinhSuaLichThi", "QuanLyLichThi", FormMethod.Post))
                {
                    <input hidden name="hidden" value="@Model.ID" />
                    <div class="form-group">
                        @Html.DisplayName("Ngày thi")
                        <div class="col-md-12">
                            <input type="date" required id="ngaythi" name="Ngaythi" value="@ConvertDate.getStrDate(@Model.NgayThi)"  />
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.DisplayName("Phòng thi")
                        <div class="col-md-12">
                            <select name="Phongthi" required>
                                @{
                                    if (ViewBag.DSPH != null)
                                    {
                                        List<tb_PhongHoc> dsph = (List<tb_PhongHoc>)ViewBag.DSPH;
                                        foreach (var item in dsph)
                                        {
                                            if (item.ID == Model.PhongThi)
                                            {
                                                <option selected value="@item.ID">
                                                    @item.MaPhongHoc
                                                </option>
                                            }
                                            else
                                            {
                                                <option value="@item.ID">
                                                    @item.MaPhongHoc
                                                </option>
                                            }
                                        }
                                    }

                                }
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.DisplayName("Giờ bắt đầu")
                        <div class="col-md-12">
                            <input type="text" required id="giobatdau" name="Giobatdau" value="@Model.GioBatDau" />
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.DisplayName("Thời lượng (phút)")
                        <div class="col-md-12">
                            <input type="number" min="0" required id="thoiluong" name="Thoiluong" value="@Model.ThoiLuong" />
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.DisplayName("Giám thị 1")
                        <div class="col-md-12">
                            <select name="GiamThi1" required>
                                @{
                                    foreach (var item in gv)
                                    {
                                        if (item.ID == Model.ID_GiamThi1)
                                        {
                                            <option selected value="@item.ID">
                                                @item.tb_ThongTinCaNhan.Hoten
                                            </option>
                                        }
                                        else
                                        {
                                            <option value="@item.ID">
                                                @item.tb_ThongTinCaNhan.Hoten
                                            </option>
                                        }
                                    }
                                }
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.DisplayName("Giám thị 2")
                        <div class="col-md-12">

                        </div>
                        <select name="GiamThi2" required>
                            @{
                                foreach (var item in gv)
                                {
                                    if (item.ID == Model.ID_GiamThi2)
                                    {
                                        <option selected value="@item.ID">
                                            @item.tb_ThongTinCaNhan.Hoten
                                        </option>
                                    }
                                    else
                                    {
                                        <option value="@item.ID">
                                            @item.tb_ThongTinCaNhan.Hoten
                                        </option>
                                    }
                                }
                            }
                        </select>
                    </div>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        <button type="submit" class="btn btn-primary me-md-2">
                            Xác nhận
                        </button>
                    </div>
                    }
                </div>
        </div>
    </div>
</div>

QuanLyTruongDaiHoc/QuanLyTruongDaiHoc/Areas/Admin/Views/QuanLyLichThi/DanhSachKhoaHocLichThi.cshtml
@model IEnumerable<QuanLyTruongDaiHoc.Models.tb_KhoaHoc>

@{
    ViewBag.Title = "DanhSachKhoaHocLichThi";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.css" />

<section class="content">
    <div class="container-fluid">
        <br />
        <br />
        <div class="row">

            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Danh sách khoá học</h4>
                    </div>
                    <div class="card-body">
                        <table class="table table-bordered table-hover" id="khoahoc">
                            @{

                                int i = 1;
                                <thead>
                                    <tr>
                                        <th>STT</th>
                                        <th>
                                            @Html.DisplayName("Mã khoá học")
                                        </th>
                                        <th>
                                            @Html.DisplayName("Tên môn học")
                                        </th>
                                        <th>
                                            @Html.DisplayName("Mã giảng viên")
                                        </th>
                                        <th>
                                            @Html.DisplayName("Số lịch thi")
                                        </th>
                                        <th>
                                            Chức năng
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        var soLich = item.tb_ThongTinNgayThi.Count();
                                        <tr>
                                            <td>@i</td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.MaKhoaHoc)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.tb_Monhoc.TenMonHoc)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.tb_GiangVien.MaGiangVien)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => soLich)
                                            </td>
                                            <td>
                                                @Html.ActionLink("Xem lịch thi", "XemLichThi", "QuanLyLichThi", new { id = item.ID }, new { @class = "btn btn-sm btn-success" })
                                            </td>
                                        </tr>
                                        i++;
                                    }
                                </tbody>
                            }
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>





<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.js"></script>

<script src="https://code.jquery.com/jquery-3.7.0.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>

<script>
    var table = new DataTable('#khoahoc', {
        language: {
            url: '//cdn.datatables.net/plug-ins/1.13.6/i18n/vi.json',
        },
    });

</script>

QuanLyTruongDaiHoc/QuanLyTruongDaiHoc/Areas/Admin/Views/QuanLyLichThi/DanhSachSinhVienDangKy.cshtml
@model IEnumerable<QuanLyTruongDaiHoc.Models.tb_DangKyMonHoc>
@using QuanLyTruongDaiHoc.Models;

<link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.css" />
<div class="card" id="dssvdk">
    <div class="card-header">Sinh viên đăng ký khoá học</div>
    <div class="card-body">
        <table class="table table-bordered table-hover" id="dsdk1">
            <thead>
                <tr>
                    <th></th>
                    <th>
                        Mã sinh viên
                    </th>
                    <th>
                        Họ tên sinh viên
                    </th>
                    <th>
                        Ngành học
                    </th>
                </tr>
            </thead>

            <tbody>
                @{
                    var ctlt = (List<tb_ChiTietLichThi>)ViewBag.CTLT;
                    foreach (var item in Model)
                    {
                                <tr>
                                    @{
                                        if (ctlt != null)
                                        {
                                            var ct = ctlt.SingleOrDefault(n => n.ID_SinhVien == item.ID_SinhVien);
                                            if (ct != null)
                                            {
                                                <td><input type="checkbox" name="Check-@item.ID_SinhVien" checked onclick="CheckDs(this)" value="@item.ID" /></td>
                                            }
                                            else
                                            {
                                                <td><input type="checkbox" name="Check-@item.ID_SinhVien" onclick="CheckDs(this)" value="@item.ID" /></td>
                                            }
                                        }
                                        else
                                        {
                                            <td>
                                                <input type="checkbox" class="checkinput" name="Check-@item.ID_SinhVien" onclick="CheckDs(this)" value="@item.ID"/>
                                                ll
                                    </td>
                                        
                                            }

                                    }
                                    <td>
                                        @Html.DisplayFor(modelItem => item.tb_SinhVien.MaSinhVien)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.tb_SinhVien.tb_ThongTinCaNhan.Hoten)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.tb_SinhVien.tb_Nganh.MaNganh)
                                    </td>
                                </tr>
                    }
                }
            </tbody>


        </table>
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.7.0.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>
<script>

</script>

<script>


    var table1 = new DataTable('#dsdk1', {
        language: {
            url: '//cdn.datatables.net/plug-ins/1.13.6/i18n/vi.json',
        },
    });
    var toastMixin = Swal.mixin({
        toast: true,
        icon: 'success',
        title: 'General Title',
        animation: false,
        position: 'top-right',
        showConfirmButton: false,
        timer: 3000,
        timerProgressBar: true,
        didOpen: (toast) => {
            toast.addEventListener('mouseenter', Swal.stopTimer)
            toast.addEventListener('mouseleave', Swal.resumeTimer)
        }
    });
    function CheckDs(element) {
        if (element.checked == true) {
            const url = new URL('@Url.Action("ThemSVPhongThi", "QuanLyLichThi")', location.origin);
            url.searchParams.set('id', element.value);
            url.searchParams.set('idlt', @ViewBag.ID_PT);
            $('#dssvpt').load(url.href);
        }

        else {
            const url = new URL('@Url.Action("LoaiBoSvPhongThi2", "QuanLyLichThi")', location.origin);
            url.searchParams.set('id', element.value);
            $('#dssvpt').load(url.href);
        }
    }
</script>


<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.10.1/dist/sweetalert2.all.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

QuanLyTruongDaiHoc/QuanLyTruongDaiHoc/Areas/Admin/Views/QuanLyLichThi/SinhVienPhongThi.cshtml
@model IEnumerable<QuanLyTruongDaiHoc.Models.tb_ChiTietLichThi>


<link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.css" />

<div class="card" id="dssvpt">
    <div class="card-header">Sinh viên thuộc phòng thi</div>
    <div class="card-body">
        <table class="table table-bordered table-hover" id="svpt">
            <thead>
                <tr>
                    <th>Xóa</th>
                    <th>
                        @Html.DisplayNameFor(model => model.tb_SinhVien.MaSinhVien)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.tb_SinhVien.tb_ThongTinCaNhan.Hoten)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.tb_SinhVien.tb_Nganh.TenNganh)
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    var sv = item.tb_SinhVien;
                    var kh = item.tb_ThongTinNgayThi.tb_KhoaHoc;
                    var dk = sv.tb_DangKyMonHoc.SingleOrDefault(n => n.ID_KhoaHoc == kh.ID);
                    <tr id="tr-@dk.ID">
                        <td><a href="#" style="color:red" onclick="LoaiSVPhongThi('@dk.ID')">&#x2716;</a></td>
                        <td>
                            @Html.DisplayFor(modelItem => item.tb_SinhVien.MaSinhVien)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.tb_SinhVien.tb_ThongTinCaNhan.Hoten)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.tb_SinhVien.tb_Nganh.TenNganh)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.js"></script>




<script src="https://code.jquery.com/jquery-3.7.0.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>

<script>
    function LoaiSVPhongThi(value) {
        var tr = document.getElementById(`tr-${value}`);
        tr.remove();
        const url = new URL('@Url.Action("LoaiBoSvPhongThi", "QuanLyLichThi")', location.origin);
        url.searchParams.set('id',value);
        $('#dssvdk').load(url.href);
    }
</script>


<script>


    var table = new DataTable('#svpt', {
        language: {
            url: '//cdn.datatables.net/plug-ins/1.13.6/i18n/vi.json',
        },
    });

</script>

QuanLyTruongDaiHoc/QuanLyTruongDaiHoc/Areas/Admin/Views/QuanLyLichThi/XemPhongThi.cshtml
@model IEnumerable<QuanLyTruongDaiHoc.Models.tb_DangKyMonHoc>

@using QuanLyTruongDaiHoc.Models;

@{
    ViewBag.Title = "XemPhongThi";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    var lt = (tb_ThongTinNgayThi)ViewBag.LT;
}


<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                            <button type="button" class="btn btn-lg btn-primary me-md-2" data-toggle="modal" data-target="#modalChinhSuaLichThi">
                                Chỉnh sửa lịch thi
                            </button>
                            @Html.Action("ChinhSuaLichThi", "QuanLyLichThi", new { id = lt.ID })
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-lg-12">
                @Html.Action("DanhSachSinhVienDangKy", "QuanLyLichThi", new { id = lt.ID })
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                @Html.Action("SinhVienPhongThi", "QuanLyLichThi", new { id = lt.ID })
            </div>
        </div>

    </div>
</section>


<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.10.1/dist/sweetalert2.all.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
    var toastMixin = Swal.mixin({
        toast: true,
        icon: 'success',
        title: 'General Title',
        animation: false,
        position: 'top-right',
        showConfirmButton: false,
        timer: 3000,
        timerProgressBar: true,
        didOpen: (toast) => {
            toast.addEventListener('mouseenter', Swal.stopTimer)
            toast.addEventListener('mouseleave', Swal.resumeTimer)
        }
    });
</script>

@{
    if (Session["SuccessChinhSuaLichThi"] != null)
    {
        <script>
            var toastMixin = Swal.mixin({
                toast: true,
                icon: 'success',
                title: 'General Title',
                animation: false,
                position: 'top-right',
                showConfirmButton: false,
                timer: 3000,
                timerProgressBar: true,
                didOpen: (toast) => {
                    toast.addEventListener('mouseenter', Swal.stopTimer)
                    toast.addEventListener('mouseleave', Swal.resumeTimer)
                }
            });
             window.onload = (event) => {
                toastMixin.fire({
                animation: true,
                title: '@Session["SuccessChinhSuaLichThi"]',
                icon: 'success'
                });
             }
        </script>
        Session["SuccessChinhSuaLichThi"] = null;
    }
}

QuanLyTruongDaiHoc/QuanLyTruongDaiHoc/Areas/Admin/Views/QuanLyLichThi/XoaLichThi.cshtml
@model QuanLyTruongDaiHoc.Models.tb_ThongTinNgayThi

<div class="modal fade" id="modalXoaLichThi-@Model.ID">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <div class="modal-header">
                <h4 class="modal-title">Thông báo</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <label> Bạn có muốn xóa lịch thi mã <strong style="color:red;">@Model.ID</strong> không?</label>

            </div>

            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Hủy</button>
                @Html.ActionLink("Xóa", "XacNhanXoaLichThi", "QuanLyLichThi", new { id = Model.ID }, new { @class = "btn btn-danger" })

            </div>


        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->