QuanLyTruongDaiHoc/QuanLyTruongDaiHoc/Areas/Admin/Controllers/PhongHocController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLyTruongDaiHoc.Models;

namespace QuanLyTruongDaiHoc.Areas.Admin.Controllers
{
    public class PhongHocController : Controller
    {
        private QuanLyDaiHocEntities db = new QuanLyDaiHocEntities();

        bool checkLogin(string prevUrl)
        {
            if (Session["TaikhoanQT"] == null)
            {
                Session["PreviousURL"] = "~/Admin/PhongHoc/" + prevUrl;
                Session["LoaiTK"] = Init.TaiKhoanQT;
                return false;
            }
            return true;
        }
        // GET: Admin/PhongHoc
        public ActionResult DanhSachPhongHoc()
        {
            if (!checkLogin("DanhSachPhongHoc"))
            {
                return RedirectToAction("DangNhap", "Admin");
            }
            var loaiphong = db.tb_LoaiPhong;
            if (loaiphong != null)
            {
                ViewBag.LoaiPhong = loaiphong.ToList();
            }
            return View(db.tb_PhongHoc.ToList());
        }

        public ActionResult ChiTietPhongHoc(int id)
        {
            var phong = db.tb_PhongHoc.Find(id);
            return PartialView(phong);
        }


        [HttpPost]
        public ActionResult ChiTietPhongHoc(FormCollection collection)
        {
            var maPhongHoc = collection["MaPhongHoc"];
            var viTri = collection["ViTri"];
            var loaiPhonghoc = int.Parse(collection["LoaiPhongHoc"]);
            var sucChua = collection["SucChua"];
            var trangThai = collection["TrangThai"];
            int id = int.Parse(collection["ID"]);

            tb_PhongHoc phong = db.tb_PhongHoc.Find(id);
            if (phong != null)
            {
                phong.MaPhongHoc = maPhongHoc;
                phong.ViTri = viTri;
                phong.ID_LoaiPhong = loaiPhonghoc;
                phong.TrangThai = bool.Parse(trangThai);
                phong.SucChua = int.Parse(sucChua);

                db.Entry(phong).State = EntityState.Modified;
                db.SaveChanges();
                Session["SuaPhong"] = "Sửa phòng "+phong.MaPhongHoc+" thành công";

            }
            return RedirectToAction("DanhSachPhongHoc");
        }


        public ActionResult ThemPhong()
        {
            return PartialView();
        }
        [HttpPost]
        public ActionResult ThemPhong(FormCollection collection)
        {
            var maPhongHoc = collection["MaPhongHoc"];
            var viTri = collection["ViTri"];
            var loaiPhonghoc = int.Parse(collection["LoaiPhongHoc"]);
            var sucChua = collection["SucChua"];
            var trangThai = collection["TrangThai"];

            tb_PhongHoc phong = new tb_PhongHoc();
            phong.MaPhongHoc = maPhongHoc;
            phong.ViTri = viTri;
            phong.ID_LoaiPhong = loaiPhonghoc;
            phong.TrangThai = bool.Parse(trangThai);
            phong.SucChua = int.Parse(sucChua);

            db.tb_PhongHoc.Add(phong);

            try
            {
                db.SaveChanges();
                Session["ThemPhong"] = "Thêm phòng " + phong.MaPhongHoc + " thành công";
            }
            catch (Exception)
            {
                Session["LoiThemPhong"] = "Không thể thêm phòng";
            }


            return RedirectToAction("DanhSachPhongHoc");
        }

        public ActionResult XoaPhong(int id)
        {
            var phong = db.tb_PhongHoc.Find(id);
            return PartialView(phong);
        }


        public ActionResult XacNhanXoaPhong(int id)
        {
            tb_PhongHoc phong = db.tb_PhongHoc.Find(id);
            string maPhong = phong.MaPhongHoc;
            db.tb_PhongHoc.Remove(phong);
            try
            {
                db.SaveChanges();
                Session["XoaPhong"] = "Xóa phòng " + maPhong + " thành công";
            }
            catch
            {
                Session["LoiXoaPhong"] = "Không thể xóa phòng " + maPhong;
            }

            return RedirectToAction("DanhSachPhongHoc");
        }

        public ActionResult QuanLyLoaiPhong()
        {
            var loaiPhong = db.tb_LoaiPhong;
            if (loaiPhong != null)
            {
                return View(loaiPhong.ToList());
            }
            return View(new List<tb_LoaiPhong>());
        }

        public ActionResult ThemLoaiPhong()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult ThemLoaiPhong(FormCollection collection)
        {
            var tenloai = collection["Tenloai"];
            tb_LoaiPhong lp = new tb_LoaiPhong();
            lp.Ten = tenloai;
            db.tb_LoaiPhong.Add(lp);
            db.SaveChanges();
            Session["SuccessThemLoaiPhong"] = "Thêm loại phòng " + tenloai + " thành công";
            return RedirectToAction("QuanLyLoaiPhong");
        }
        public ActionResult XoaLoaiPhong(int id)
        {
            var lp = db.tb_LoaiPhong.Find(id);
            return PartialView(lp);
        }


        public ActionResult XacNhanXoaLoaiPhong(int id)
        {
            tb_LoaiPhong lp = db.tb_LoaiPhong.Find(id);
            db.tb_LoaiPhong.Remove(lp);
            try
            {
                db.SaveChanges();
                Session["SuccessXoaLoaiPhong"] = "Xóa loại phòng " + lp.Ten.ToLower() + " thành công";
            }
            catch
            {
                Session["ErrorXoaLoaiPhong"] = "Không thể xóa loại phòng " + lp.Ten.ToLower() + " vì đang được sử dụng";
            }
            return RedirectToAction("QuanLyLoaiPhong");
        }


    }
}

QuanLyTruongDaiHoc/QuanLyTruongDaiHoc/Areas/Admin/Views/PhongHoc/ChiTietPhongHoc.cshtml
@model QuanLyTruongDaiHoc.Models.tb_PhongHoc
<div class="modal fade" id="modalChiTietPhongHoc-@Model.ID">
    <div class="modal-dialog modal-xl modal-dialog-centered">
        <div class="modal-content">
            @using (Html.BeginForm("ChiTietPhongHoc", "PhongHoc", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="modal-header">
                    <h4 class="modal-title">Chi tiết phòng học</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.ID)
                    <div class="form-horizontal">
                        <div class="col-md-12">
                            <label>Mã Phòng Học:</label>
                            <div class="form-group">
                                <input type="text" name="MaPhongHoc" id="MaPhongHoc-@Model.ID" value="@Model.MaPhongHoc"  class="form-control" />
                            </div>

                        </div>
                        <div class="col-md-12">
                            <label>Loại Phòng Học:</label>
                            <div class="form-group">
                                <select name="LoaiPhongHoc" class="form-control" >
                                    <option value="Lý thuyết" selected>Lý thuyết</option>
                                    <option value="Thực hành">Thực hành</option>
                                </select>
                                @*<input type="text" name="LoaiPhongHoc" id="LoaiPhongHoc-@Model.ID" value="@Model.LoaiPhongHoc"  class="form-control" />*@
                            </div>

                        </div>
                        <div class="col-md-12">
                            <label>Vị trí:</label>
                            <div class="form-group">
                                <textarea class="form-control" name="ViTri" id="ViTri-@Model.ID" >@Model.ViTri</textarea>
                            </div>

                        </div>
                        <div class="col-md-12">
                            <label>Sức chứa</label>
                            <div class="form-group">
                                <input type="number" name="SucChua" id="SucChua-@Model.ID" value="@Model.SucChua"  min="0" max="999" class="form-control" />
                            </div>

                        </div>
                        @*<div class="col-md-12" id="lbTrangThai-@Model.ID">
                            <label>Trạng thái:  <label style="color:@(Model.TrangThai==true?"green":"red")">@(Model.TrangThai == true ? "Đang sử dụng":"Bảo trì")</label></label>
                            

                        </div>*@
                        <div class="col-md-12" id="rdiTrangThai-@Model.ID" >
                            <label>Trạng thái:</label>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" id="TrangThai1" name="TrangThai" value="true" @(Model.TrangThai==true?"checked":"") >
                                <label class="form-check-label" for="TrangThai1">
                                    Hoạt động
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" id="TrangThai2" name="TrangThai" value="false"  @(Model.TrangThai==false?"checked":"")>
                                <label class="form-check-label" for="TrangThai2">
                                    Bảo trì
                                </label>
                            </div>

                        </div>


                    </div>


                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Hủy</button>
                    
                    <div class="row">

                        @*<a href="#" class="btn btn-danger" onclick="suathongtin(this.id)" id="Huy-@Model.ID" hidden>Hủy</a>
                        <button type="submit" class="btn btn-success" id="Luu-@Model.ID" hidden>Lưu</button>*@
                        <button   class="btn btn-primary" onclick="suathongtin(this.id)" id="Sua-@Model.ID">Sửa thông tin</button>
                    </div>
                    
                </div>
            }
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

@*<script>
    function suathongtin(id) {
        if (id == 'Sua-@Model.ID') {
            document.getElementById('Sua-@Model.ID').hidden = true;
            document.getElementById('Huy-@Model.ID').hidden = false;
            document.getElementById('Luu-@Model.ID').hidden = false;

            console.log(2);

            document.getElementById('MaPhongHoc-@Model.ID').disabled = false;
            document.getElementById('ViTri-@Model.ID').disabled = false;
            document.getElementById('LoaiPhongHoc-@Model.ID').disabled = false;
            document.getElementById('SucChua-@Model.ID').disabled = false;

            document.getElementById('lbTrangThai-@Model.ID').hidden = true;
            document.getElementById('rdiTrangThai-@Model.ID').hidden = false;

        }
        else if (id == 'Huy-@Model.ID') {
            document.getElementById('Sua-@Model.ID').hidden = false;
            document.getElementById('Huy-@Model.ID').hidden = true;
            document.getElementById('Luu-@Model.ID').hidden = true;

            document.getElementById('MaPhongHoc-@Model.ID').disabled = true;
            document.getElementById('ViTri-@Model.ID').disabled = true;
            document.getElementById('LoaiPhongHoc-@Model.ID').disabled = true;
            document.getElementById('SucChua-@Model.ID').disabled = true;

            document.getElementById('lbTrangThai-@Model.ID').hidden = false;
            document.getElementById('rdiTrangThai-@Model.ID').hidden = true;


        }
        else {
            document.getElementById('Sua-@Model.ID').hidden = false;
            document.getElementById('Huy-@Model.ID').hidden = true;
            document.getElementById('Luu-@Model.ID').hidden = true;

            document.getElementById('MaPhongHoc-@Model.ID').disabled = true;
            document.getElementById('ViTri-@Model.ID').disabled = true;
            document.getElementById('LoaiPhongHoc-@Model.ID').disabled = true;
            document.getElementById('SucChua-@Model.ID').disabled = true;

            document.getElementById('lbTrangThai-@Model.ID').hidden = false;
            document.getElementById('rdiTrangThai-@Model.ID').hidden = true;
        }
    }

</script>*@

QuanLyTruongDaiHoc/QuanLyTruongDaiHoc/Areas/Admin/Views/PhongHoc/DanhSachPhongHoc.cshtml
@model IEnumerable<QuanLyTruongDaiHoc.Models.tb_PhongHoc>
@using QuanLyTruongDaiHoc.Models;
@{
    ViewBag.Title = "DanhSachPhongHoc";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


@Html.Action("ThemPhong", "PhongHoc")

<section class="content">
    <div class="container-fluid">
        <br />
        <div class="row">
            <div class="card col-12">
                <div class="card-header">
                    <h4>Danh sách phòng học hiện hành</h4>
                </div>
                <div class="card-header">
                    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                        <button type="button" class="btn btn-lg btn-primary me-md-2" data-toggle="modal" data-target="#modalThemPhong">
                            Thêm Phòng
                        </button>
                    </div>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        @Html.ActionLink("Quản lý loại phòng", "QuanLyLoaiPhong", "PhongHoc", null, new { @class = "btn btn-primary me-md-2" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row">

            <div class="card col-12">
                @{
                    var loaiphong = (List<tb_LoaiPhong>)ViewBag.LoaiPhong;
                    foreach (var item in loaiphong)
                    {
                        <div class="card-header">
                            <h3>Phòng @item.Ten.ToLower()</h3>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                @{
                                    foreach (var phong in Model)
                                    {
                                        if (phong.ID_LoaiPhong == item.ID)
                                        {
                                            if (phong.TrangThai)
                                            {
                                                <div class="col-md-3">
                                                    <div class="small-box bg-info">
                                                        <button data-toggle="modal" data-target="#modalXoaPhong-@item.ID" class="btn btn-sm btn-warning">Xóa</button>
                                                        <div class="inner">
                                                            <h3>@phong.MaPhongHoc</h3>

                                                            <p>@phong.SucChua</p>
                                                            <label> @phong.ViTri</label>
                                                        </div>
                                                        <div class="icon">
                                                            <i class="nav-icon fa fa-book"></i>
                                                        </div>
                                                        <a href="#" data-toggle="modal" data-target="#modalChiTietPhongHoc-@item.ID" class="small-box-footer">Chi tiết <i class="fas fa-arrow-circle-right"></i></a>

                                                    </div>
                                                </div>
                                            }
                                            else
                                            {
                                                <div class="col-md-3">
                                                    <div class="small-box bg-danger">
                                                        <button data-toggle="modal" data-target="#modalXoaPhong-@item.ID" class="btn btn-sm btn-warning">Xóa</button>
                                                        <div class="inner">
                                                            <h3>@phong.MaPhongHoc</h3>

                                                            <p>@phong.SucChua</p>
                                                            <label><i>Đang bảo trì</i></label>
                                                        </div>
                                                        <div class="icon">
                                                            <i class="nav-icon fa fa-book"></i>
                                                        </div>
                                                        <a href="#" data-toggle="modal" data-target="#modalChiTietPhongHoc-@item.ID" class="small-box-footer">Chi tiết <i class="fas fa-arrow-circle-right"></i></a>
                                                    </div>
                                                </div>
                                            }
                                            @Html.Action("ChiTietPhongHoc", "PhongHoc", new { id = item.ID })
                                            @Html.Action("XoaPhong", "PhongHoc", new { id = item.ID })
                                        }
                                    }
                                }
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</section>




<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.10.1/dist/sweetalert2.all.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
@{
    if (Session["SuaPhong"] != null)
    {
        <script>
            var toastMixin = Swal.mixin({
                toast: true,
                icon: 'success',
                title: 'General Title',
                animation: false,
                position: 'top-right',
                showConfirmButton: false,
                timer: 3000,
                timerProgressBar: true,
                didOpen: (toast) => {
                    toast.addEventListener('mouseenter', Swal.stopTimer)
                    toast.addEventListener('mouseleave', Swal.resumeTimer)
                }
            });
             window.onload = (event) => {
                toastMixin.fire({
                animation: true,
                title: '@Session["SuaPhong"]',
                icon: 'success'
                });
             }
        </script>
        Session["SuaPhong"] = null;
    }
    if (Session["ThemPhong"] != null)
    {
        <script>
            var toastMixin = Swal.mixin({
                toast: true,
                icon: 'success',
                title: 'General Title',
                animation: false,
                position: 'top-right',
                showConfirmButton: false,
                timer: 3000,
                timerProgressBar: true,
                didOpen: (toast) => {
                    toast.addEventListener('mouseenter', Swal.stopTimer)
                    toast.addEventListener('mouseleave', Swal.resumeTimer)
                }
            });
             window.onload = (event) => {
                toastMixin.fire({
                animation: true,
                title: '@Session["ThemPhong"]',
                icon: 'success'
                });
             }
        </script>
        Session["ThemPhong"] = null;
    }
    else if (Session["LoiThemPhong"] != null)
    {
        <script>
            var toastMixin = Swal.mixin({
                toast: true,
                icon: 'success',
                title: 'General Title',
                animation: false,
                position: 'top-right',
                showConfirmButton: false,
                timer: 3000,
                timerProgressBar: true,
                didOpen: (toast) => {
                    toast.addEventListener('mouseenter', Swal.stopTimer)
                    toast.addEventListener('mouseleave', Swal.resumeTimer)
                }
            });
             window.onload = (event) => {
                toastMixin.fire({
                animation: true,
                title: '@Session["LoiThemPhong"]',
                icon: 'error'
                });
             }
        </script>
        Session["LoiThemPhong"] = null;
    }
    if (Session["XoaPhong"] != null)
    {
        <script>
            var toastMixin = Swal.mixin({
                toast: true,
                icon: 'success',
                title: 'General Title',
                animation: false,
                position: 'top-right',
                showConfirmButton: false,
                timer: 3000,
                timerProgressBar: true,
                didOpen: (toast) => {
                    toast.addEventListener('mouseenter', Swal.stopTimer)
                    toast.addEventListener('mouseleave', Swal.resumeTimer)
                }
            });
             window.onload = (event) => {
                toastMixin.fire({
                animation: true,
                title: '@Session["XoaPhong"]',
                icon: 'success'
                });
             }
        </script>
        Session["XoaPhong"] = null;
    }
    else if (Session["LoiXoaPhong"] != null)
    {
        <script>
            var toastMixin = Swal.mixin({
                toast: true,
                icon: 'success',
                title: 'General Title',
                animation: false,
                position: 'top-right',
                showConfirmButton: false,
                timer: 3000,
                timerProgressBar: true,
                didOpen: (toast) => {
                    toast.addEventListener('mouseenter', Swal.stopTimer)
                    toast.addEventListener('mouseleave', Swal.resumeTimer)
                }
            });
             window.onload = (event) => {
                toastMixin.fire({
                animation: true,
                title: '@Session["LoiXoaPhong"]',
                icon: 'error'
                });
             }
        </script>
        Session["LoiXoaPhong"] = null;
    }

}

QuanLyTruongDaiHoc/QuanLyTruongDaiHoc/Areas/Admin/Views/PhongHoc/QuanLyLoaiPhong.cshtml
@model IEnumerable<QuanLyTruongDaiHoc.Models.tb_LoaiPhong>
@{
    ViewBag.Title = "QuanLyLoaiPhong";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


@Html.Action("ThemLoaiPhong", "PhongHoc")
<section class="content">
    <div class="container-fluid">
        <br />
        <div class="row">
            <div class="card col-12">
                <div class="card-header">
                    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                        <button type="button" class="btn btn-lg btn-primary me-md-2" data-toggle="modal" data-target="#modalThemLoaiPhong">
                            Thêm loại phòng
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">

            <div class="card col-12">
                <div class="card-header">
                    <h3>Danh sách loại phòng</h3>
                </div>
                <div class="card-body">
                    <div class="row">
                        @{
                            foreach (var item in Model)
                            {
                                <div class="col-md-3">
                                    <div class="small-box bg-info">
                                        <button data-toggle="modal" data-target="#modalXoaLoaiPhong-@item.ID" class="btn btn-sm btn-warning">Xóa</button>
                                        <div class="inner">
                                            <h3>@item.Ten</h3>
                                        </div>
                                        <div class="icon">
                                            <i class="nav-icon fa fa-book"></i>
                                        </div>
                                    </div>
                                </div>
                                @Html.Action("XoaLoaiPhong", "PhongHoc", new { id = item.ID })
                            }
                        }
                    </div>
                </div>
                <div class="card-footer">
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        @Html.ActionLink("Quay lại quản lý phòng học", "DanhSachPhongHoc", "PhongHoc", null, new { @class = "btn btn-primary me-md-2" })
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.10.1/dist/sweetalert2.all.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
@{
    if (Session["SuccessThemLoaiPhong"] != null)
    {
        <script>
            var toastMixin = Swal.mixin({
                toast: true,
                icon: 'success',
                title: 'General Title',
                animation: false,
                position: 'top-right',
                showConfirmButton: false,
                timer: 3000,
                timerProgressBar: true,
                didOpen: (toast) => {
                    toast.addEventListener('mouseenter', Swal.stopTimer)
                    toast.addEventListener('mouseleave', Swal.resumeTimer)
                }
            });
             window.onload = (event) => {
                toastMixin.fire({
                animation: true,
                title: '@Session["SuccessThemLoaiPhong"]',
                icon: 'success'
                });
             }
        </script>
        Session["SuccessThemLoaiPhong"] = null;
    }
    if (Session["SuccessXoaLoaiPhong"] != null)
    {
        <script>
            var toastMixin = Swal.mixin({
                toast: true,
                icon: 'success',
                title: 'General Title',
                animation: false,
                position: 'top-right',
                showConfirmButton: false,
                timer: 3000,
                timerProgressBar: true,
                didOpen: (toast) => {
                    toast.addEventListener('mouseenter', Swal.stopTimer)
                    toast.addEventListener('mouseleave', Swal.resumeTimer)
                }
            });
             window.onload = (event) => {
                toastMixin.fire({
                animation: true,
                title: '@Session["SuccessXoaLoaiPhong"]',
                icon: 'success'
                });
             }
        </script>
        Session["SuccessXoaLoaiPhong"] = null;
    }
    if (Session["ErrorXoaLoaiPhong"] != null)
    {
        <script>
            var toastMixin = Swal.mixin({
                toast: true,
                icon: 'success',
                title: 'General Title',
                animation: false,
                position: 'top-right',
                showConfirmButton: false,
                timer: 3000,
                timerProgressBar: true,
                didOpen: (toast) => {
                    toast.addEventListener('mouseenter', Swal.stopTimer)
                    toast.addEventListener('mouseleave', Swal.resumeTimer)
                }
            });
             window.onload = (event) => {
                toastMixin.fire({
                animation: true,
                title: '@Session["ErrorXoaLoaiPhong"]',
                icon: 'error'
                });
             }
        </script>
        Session["ErrorXoaLoaiPhong"] = null;
    }
}

QuanLyTruongDaiHoc/QuanLyTruongDaiHoc/Areas/Admin/Views/PhongHoc/ThemLoaiPhong.cshtml
<div class="modal fade" id="modalThemLoaiPhong">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            @using (Html.BeginForm("ThemLoaiPhong", "PhongHoc", FormMethod.Post))
            {
                <div class="modal-header">
                    <h4 class="modal-title">Thêm loại phòng mới</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <div class="col-md-12">
                            <label>Tên loại:</label>
                            <div class="form-group">
                                <input type="text" required name="Tenloai" id="tenloai" class="form-control" />
                            </div>

                        </div>
                    </div>
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Hủy</button>

                    <div class="row">
                        <button type="submit" class="btn btn-primary">Thêm</button>
                    </div>

                </div>
            }
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

QuanLyTruongDaiHoc/QuanLyTruongDaiHoc/Areas/Admin/Views/PhongHoc/XoaLoaiPhong.cshtml
@model QuanLyTruongDaiHoc.Models.tb_LoaiPhong

<div class="modal fade" id="modalXoaLoaiPhong-@Model.ID">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <div class="modal-header">
                <h4 class="modal-title">Thông báo</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <label> Bạn có muốn xóa loại phòng <strong style="color:red;">@Model.Ten</strong> không?</label>

            </div>

            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Hủy</button>
                @Html.ActionLink("Xóa", "XacNhanXoaLoaiPhong", "PhongHoc", new { id = Model.ID }, new { @class = "btn btn-danger" })

            </div>

        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->