QuanLyTruongDaiHoc/QuanLyTruongDaiHoc/Areas/Admin/Controllers/XinNghiPhepController.cs
using QuanLyTruongDaiHoc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyTruongDaiHoc.Areas.Admin.Controllers
{
    public class XinNghiPhepController : Controller
    {
        // GET: Admin/XinNghiPhep
        bool checkLogin(string prevUrl)
        {
            if (Session["TaikhoanQT"] == null)
            {
                Session["PreviousURL"] = "~/Admin/XinNghiPhep/" + prevUrl;
                Session["LoaiTK"] = Init.TaiKhoanQT;
                return false;
            }
            return true;
        }

        private QuanLyDaiHocEntities db = new QuanLyDaiHocEntities();

        public ActionResult XemDanhSachNghiPhep()
        {
            if (!checkLogin("XemDanhSachNghiPhep"))
            {
                return RedirectToAction("DangNhap", "Admin");
            }
            var ds = db.tb_DangKyNghiPhep.OrderBy(n => n.NgayGui);
            return View(ds);
        }

        public ActionResult XuLyDon(int? id)
        {
            var don = db.tb_DangKyNghiPhep.SingleOrDefault(n => n.ID == id);
            return PartialView(don);
        }
        
        [HttpPost]
        public ActionResult XuLyDon(FormCollection collection)
        {
            int? id = int.Parse(collection["id_don"]);
            var don = db.tb_DangKyNghiPhep.SingleOrDefault(n => n.ID == id);

            don.PhanHoi = collection["PhanHoi"];
            don.NgayDuyet = DateTime.Now;
            don.TrangThai = int.Parse(collection["TrangThai"]);

            db.Entry(don).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("XemDanhSachNghiPhep");
        }
    }
}

QuanLyTruongDaiHoc/QuanLyTruongDaiHoc/Areas/Admin/Views/XinNghiPhep/XemDanhSachNghiPhep.cshtml
@using QuanLyTruongDaiHoc.Models;
@model IEnumerable<QuanLyTruongDaiHoc.Models.tb_DangKyNghiPhep>

@{
    ViewBag.Title = "XemDanhSachNghiPhep";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.css" />

<section class="content">
    <div class="container-fluid">
        <br />
        <br />
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <label> Danh sách đơn xin nghỉ phép</label>
                    </div>
                    <div class="card-body">
                        <table class="table table-bordered table-hover" id="danhsachnghiphep">
                            @{

                                int i = 1;
                                <thead>
                                    <tr>

                                        <th>STT</th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.tb_GiangVien.MaGiangVien)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.tb_GiangVien.tb_ThongTinCaNhan.Hoten)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.NgayNghi)
                                        </th>

                                        <th>
                                            @Html.DisplayNameFor(model => model.LyDo)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.NgayGui)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.TrangThai)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.PhanHoi)
                                        </th>

                                        <th>
                                            @Html.DisplayNameFor(model => model.NgayDuyet)
                                        </th>
                                        <th>Chức năng</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                    <tr>
                                        <td>@i</td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.tb_GiangVien.MaGiangVien)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.tb_GiangVien.tb_ThongTinCaNhan.Hoten)
                                        </td>

                                        <td>
                                            @Html.DisplayFor(modelItem => item.NgayNghi)
                                        </td>

                                        <td>
                                            @Html.DisplayFor(modelItem => item.LyDo)
                                        </td>
                                        <th>
                                            @Html.DisplayFor(modelItem => item.NgayGui)
                                        </th>
                                        <th>
                                            @(Init.getStrTrangThai(item.TrangThai))
                                        </th>
                                        <th>
                                            @Html.DisplayFor(modelItem => item.PhanHoi)
                                        </th>

                                        <th>
                                            @Html.DisplayFor(modelItem => item.NgayDuyet)
                                        </th>

                                            <td>
                                                <button type="button" class="btn btn-sm btn-primary" data-toggle="modal" data-target="#modalXuLyDon-@item.ID">
                                                    Xem chi tiết
                                                </button>
                                                @Html.Action("XuLyDon", "XinNghiPhep", new { id = item.ID })
                                            </td>
                                        
                                    </tr>
                                        i++;
                                    }
                                </tbody>
                            }
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script src="https://code.jquery.com/jquery-3.7.0.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>
<script>


    var table = new DataTable('#danhsachnghiphep', {
        language: {
            url: '//cdn.datatables.net/plug-ins/1.13.6/i18n/vi.json',
        },
    });

</script>

QuanLyTruongDaiHoc/QuanLyTruongDaiHoc/Areas/Admin/Views/XinNghiPhep/XuLyDon.cshtml
@using QuanLyTruongDaiHoc.Models;
@model QuanLyTruongDaiHoc.Models.tb_DangKyNghiPhep

<div class="modal fade" id="modalXuLyDon-@Model.ID">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            @using (Html.BeginForm("XuLyDon", "XinNghiPhep", FormMethod.Post))
            {
                @Html.Hidden("id_don", Model.ID)
                <div class="modal-header">
                    <h4 class="modal-title">Xử lý yêu cầu nghỉ phép</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">


                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <div class="form-group">
                            Mã giảng viên: @Model.tb_GiangVien.MaGiangVien
                        </div>
                        <div class="form-group">
                            Họ tên: @Model.tb_GiangVien.tb_ThongTinCaNhan.Hoten
                        </div>
                        <div class="form-group">
                            Ngày nghỉ: @Model.NgayNghi
                        </div>
                        <div class="form-group">
                            Lý do: @Model.LyDo
                        </div>
                        <div class="form-group">
                            Ngày gửi: @Model.NgayGui
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.TrangThai, "Trạng thái", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-12">
                                <select name="TrangThai" class="form-control">
                                    @{
                                        if (Model.TrangThai == Init.DaDuyet)
                                        {
                                            <option value="@Init.DoiDuyet">@Init.StrDoiDuyet</option>
                                            <option value="@Init.DaDuyet" selected>@Init.StrDaDuyet</option>
                                            <option value="@Init.TuChoiDuyet">@Init.StrTuChoiDuyet</option>
                                        }
                                        else if (Model.TrangThai == Init.DoiDuyet)
                                        {
                                            <option value="@Init.DoiDuyet" selected>@Init.StrDoiDuyet</option>
                                            <option value="@Init.DaDuyet">@Init.StrDaDuyet</option>
                                            <option value="@Init.TuChoiDuyet">@Init.StrTuChoiDuyet</option>
                                        }
                                        else
                                        {
                                            <option value="@Init.DoiDuyet">@Init.StrDoiDuyet</option>
                                            <option value="@Init.DaDuyet">@Init.StrDaDuyet</option>
                                            <option value="@Init.TuChoiDuyet" selected>@Init.StrTuChoiDuyet</option>
                                        }
                                    }
                                </select>
                            </div>
                        </div>


                        <div class="form-group">
                            @Html.LabelFor(model => model.PhanHoi, "Phản hồi", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-12">
                                <textarea id="Phanhoi" name="Phanhoi" class="form-control">@Model.PhanHoi</textarea>
                            </div>
                        </div>

                        @{
                            if (Model.NgayDuyet != null)
                            {
                                <div class="form-group">
                                    Thông tin yêu cầu: @Model.NgayDuyet
                                </div>
                            }
                        }


                    </div>
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Hủy</button>
                    <button type="submit" class="btn btn-primary">Lưu</button>
                </div>
            }
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>